async function startProgram() {
	setMainLed({ r: 255, g: 0, b: 0 });
	await roll(0, 90, 2);
	stopRoll();
	stopRoll();
	stopRoll();
	stopRoll();
	setMainLed({ r: 255, g: 135, b: 2 });
	await roll(180, 90, 2);
	stopRoll();
	stopRoll();
	stopRoll();
	stopRoll();
	setMainLed({ r: 255, g: 247, b: 4 });
	await roll(90, 90, 2);
	stopRoll();
	stopRoll();
	stopRoll();
	stopRoll();
	setMainLed({ r: 237, g: 20, b: 255 });
	await roll(270, 90, 2);
	stopRoll();
	stopRoll();
	stopRoll();
	stopRoll();
	setMainLed({ r: 0, g: 0, b: 255 });
	await roll(90, 90, 2);
	stopRoll();
	stopRoll();
	stopRoll();
	stopRoll();
	await roll(180, 90, 2);
	stopRoll();
	stopRoll();
	stopRoll();
	stopRoll();
	await roll(0, 90, 2);
	setMainLed({ r: 0, g: 255, b: 0 });
	await speak('Pretty good, right?', true);
}
